// UML Class Diagram
export const NODE_WIDTH = 220; // Minimum width for UML class boxes.
export const UML_FONT_SIZE = 12; // Font size for UML text (header, attributes, methods).
export const HEADER_HEIGHT = UML_FONT_SIZE + 2 * 8; // Header height = font size + top/bottom padding.
export const UML_LINE_HEIGHT = 1.6; // Line height multiplier for UML text.
export const ROW_HEIGHT = Math.round(UML_FONT_SIZE * UML_LINE_HEIGHT); // Row height for each attribute/method line.
export const SECTION_PADDING = 8; // Vertical padding above/below attribute and method sections.
export const TEXT_PADDING = 12; // Horizontal padding for text inside class boxes.
export const EDGE_CORNER_GUTTER = 40; // No-attach zone near class box corners for edge anchors.
export const EDGE_RADIUS = 2; // Corner radius for orthogonal edge bends.
export const EDGE_STUB_LENGTH = 12; // Minimum perpendicular distance from node edge before first bend.
export const REFLEXIVE_LOOP_INSET = 15; // How far reflexive loops extend outside the class box.
export const EDGE_SNAP_DELTA = 60; // Snap threshold for near-horizontal/vertical edges.
export const UML_CORNER_RADIUS = 2; // Corner radius for UML class and package boxes.
export const UML_PACKAGE_PADDING = 25; // Extra padding around classes inside package boxes.
export const EXPORT_PADDING = 5; // PNG export margin around UML content.
export const EXPORT_SCALE = 1; // PNG export scale multiplier.
export const HEADER_VERTICAL_PADDING = 8; // Vertical padding above/below class names in headers.
export const FONT_MEASURE_FALLBACK_CHAR_WIDTH = 8; // Fallback width per character when canvas context is unavailable.
export const FONT_METRICS_FALLBACK_ASCENT_RATIO = 0.8; // Estimated ascent ratio when glyph metrics are unavailable.
export const FONT_METRICS_FALLBACK_DESCENT_RATIO = 0.2; // Estimated descent ratio when glyph metrics are unavailable.
export const DEFAULT_VIEW_X = 0; // Initial pan offset (x) for the UML canvas.
export const DEFAULT_VIEW_Y = 0; // Initial pan offset (y) for the UML canvas.
export const DEFAULT_VIEW_SCALE = 1; // Initial zoom factor for the UML canvas.
export const MIN_ZOOM_SCALE = 0.4; // Lower zoom clamp to keep content usable.
export const MAX_ZOOM_SCALE = 2.5; // Upper zoom clamp to avoid excessive magnification.
export const ZOOM_STEP_IN = 1.1; // Incremental zoom-in factor.
export const ZOOM_STEP_OUT = 0.9; // Incremental zoom-out factor.
export const DRAG_MOVE_THRESHOLD_PX = 3; // Minimum pointer movement before drag is considered intentional.
export const PACKAGE_LABEL_BASELINE_OFFSET = 1; // Visual baseline correction for package labels.
