export const NODE_WIDTH = 220; // Minimum width for UML class boxes.
export const UML_FONT_SIZE = 12; // Font size for UML text (header, attributes, methods).
export const HEADER_HEIGHT = UML_FONT_SIZE + 2 * 8; // Header height = font size + top/bottom padding.
export const UML_LINE_HEIGHT = 1.6; // Line height multiplier for UML text.
export const ROW_HEIGHT = Math.round(UML_FONT_SIZE * UML_LINE_HEIGHT); // Row height for each attribute/method line.
export const SECTION_PADDING = 8; // Vertical padding above/below attribute and method sections.
export const TEXT_PADDING = 12; // Horizontal padding for text inside class boxes.
export const EDGE_CORNER_GUTTER = 40; // No-attach zone near class box corners for edge anchors.
export const EDGE_RADIUS = 2; // Corner radius for orthogonal edge bends.
export const REFLEXIVE_LOOP_INSET = 15; // How far reflexive loops extend outside the class box.
export const EDGE_SNAP_DELTA = 60; // Snap threshold for near-horizontal/vertical edges.
export const UML_CORNER_RADIUS = 2; // Corner radius for UML class and package boxes.
export const UML_PACKAGE_PADDING = 25; // Extra padding around classes inside package boxes.
export const EXPORT_PADDING = 5; // PNG export margin around UML content.
export const EXPORT_SCALE = 1.5; // PNG export scale multiplier.
export const HEADER_VERTICAL_PADDING = 8; // Vertical padding above/below class names in headers.
export const FONT_MEASURE_FALLBACK_CHAR_WIDTH = 8; // Fallback width per character when canvas context is unavailable.
export const DEFAULT_VIEW_X = 0; // Initial pan offset (x) for the UML canvas.
export const DEFAULT_VIEW_Y = 0; // Initial pan offset (y) for the UML canvas.
export const DEFAULT_VIEW_SCALE = 1; // Initial zoom factor for the UML canvas.
export const MIN_ZOOM_SCALE = 0.4; // Lower zoom clamp to keep content usable.
export const MAX_ZOOM_SCALE = 2.5; // Upper zoom clamp to avoid excessive magnification.
export const ZOOM_STEP_IN = 1.1; // Incremental zoom-in factor.
export const ZOOM_STEP_OUT = 0.9; // Incremental zoom-out factor.
export const DRAG_MOVE_THRESHOLD_PX = 3; // Minimum pointer movement before drag is considered intentional.
export const PACKAGE_LABEL_BASELINE_OFFSET = 1; // Visual baseline correction for package labels.
export const STRUCTOGRAM_FONT_SIZE = 12; // Base text size for structogram labels and statements.
export const STRUCTOGRAM_CHAR_WIDTH = 7; // Width estimate per character for structogram text measurement.
export const STRUCTOGRAM_ROW_HEIGHT = 30; // Default row height for simple structogram statements.
export const STRUCTOGRAM_HEADER_HEIGHT = 30; // Header row height for conditional/loop/container blocks.
export const STRUCTOGRAM_SECTION_HEADER_HEIGHT = 24; // Sub-header row height for switch cases and catch/finally sections.
export const STRUCTOGRAM_TEXT_PADDING_X = 10; // Horizontal text padding inside structogram cells.
export const STRUCTOGRAM_TEXT_BASELINE_OFFSET = 8; // Vertical baseline correction for structogram text.
export const STRUCTOGRAM_MIN_NODE_WIDTH = 220; // Minimum width for any structogram block.
export const STRUCTOGRAM_MIN_BRANCH_WIDTH = 140; // Minimum width for decision branch columns.
export const STRUCTOGRAM_CANVAS_PADDING = 12; // Outer padding around structogram SVG content.
